[mongodb1]
mongodb1.learndevops.fun
[redis1]
redis1.learndevops.fun
[rabbitmq1]
rabbitmq1.learndevops.fun
[mysql1]
mysql1.learndevops.fun
[cart1]
cart1.learndevops.fun
[catalogue]
catalogue.learndevops.fun
[user]
user.learndevops.fun
[shipping]
shipping.learndevops.fun
[payment]
user.learndevops.fun


[frontend]
frontend.learndevops.fun


[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory