[mongodb]
mongodb.learndevops.fun
[redis]
redis.learndevops.fun
[rabbitmq]
rabbitmq.learndevops.fun
[mysql]
mysql.learndevops.fun
[cart]
cart.learndevops.fun
[catalogue]
catalogue.learndevops.fun
[user]
user.learndevops.fun
[shipping]
shipping.learndevops.fun
[payment]
user.learndevops.fun
[frontend]
frontend.learndevops.fun


[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory